apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: sample-springboot-deployment
spec:
  selector:
    matchLabels:
      app: sample-springboot
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: sample-springboot
    spec:
      containers:
        - name: sample-springboot
          image: testdata451/sample-spring-app:1.2
          ports:
            - containerPort: 8080
---
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
kind: Service
apiVersion: v1
metadata:
  name: sample-springboot-service
spec:
  selector:
    app: sample-springboot
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000
  type: NodePort